[package]
name = "aya"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.90"
clap = { version = "4.5.20", features = ["derive"] }
serde = "1.0.214"
serde_json = "1.0.132"
serde_yaml = "0.9.34"
toml = "0.8.19"
